### ISSUE TITLE
ChosenListBox setFocus breaks tab navigation

### ISSUE THREAD

**Issue by jaros** [ArcBees/gwtchosen#103]
Given:
ChosenListBox oneCombo;
ChosenListBox twoCombo;
ChosenListBox threeCombo;

after we set focus on twoCombo: 

twoCombo.setFocus(true);

focus is set correctly 
After that we navigate by Tab/Shift+Tab between those three comboboxes twoCombo is skipped (doesn't get any focus anymore). Focus is only switched between  oneCombo and threeCombo.

**Comment by olafleur** [comment]
Closing, as this issue is more than two years old. Feel free to reopen if you still have the issue with the current version.
