### ISSUE TITLE
handler for search field keypresses

### ISSUE THREAD

**Issue by jaros** [ArcBees/gwtchosen#104]
Is it possible to have handler for search criteria changed (character input in searchField) in combobox ?
I need to reload  the list based on type in search parameter (request to service).
The initial list could be too long therefore max result is limited.
At the moment widget has keyup handler for searchField but it's private.

**Comment by olafleur** [comment]
Closing, as this issue is more than two years old. Feel free to reopen if you still have the issue with the current version.
