### ISSUE TITLE
ClickHandler is Never Fired.

### ISSUE THREAD

**Issue by airtech** [ArcBees/gwtchosen#125]
ClickHandler is never fired. Not sure why this is not a reported issue already, but I can't capture a click event - which I need to do in my application.

```
ChosenListBox clb = new ChosenListBox();
clb.addItem("hey");
clb.update();
clb.addClickHandler(new ClickHandler(){
   @Override
   public void onClick(ClickEvent event) {
      Window.alert("hey");
   }
});		
```

**Comment by olafleur** [comment]
Closing, as this issue is more than two years old. Feel free to reopen if you still have the issue with the current version.
