### ISSUE TITLE
Search fails to find items containing an apostrophe/single-quote

### ISSUE THREAD

**Issue by dnorrell** [ArcBees/gwtchosen#128]
If an item contains a ' (single-quote) character, this will not match a search expression that also contains the same character.

It looks like in ChosenImpl the search string is escaped using SafeHtmlUtils.htmlEscape that replaces a ' with &#39; - this does not seem to reliably match the item html so never returns results.

**Comment by olafleur** [comment]
Closing, as this issue is more than a year old. Feel free to reopen if you still have the issue with the current version.
