### ISSUE TITLE
Broken link in widget sample

### ISSUE THREAD

**Issue by rdwallis** [ArcBees/gwtchosen#160]
http://arcbees.github.io/gwtchosen/widgetsample/index.html 

Source code link goes to:
https://github.com/jDramaix/gwtchosen/tree/master/sample/src/main/java/com/watopi/chosen/widgetsample

which doesn't exist anymore.

**Comment by spg** [comment]
@rdwallis widget samples have moved to http://arcbees.github.io/gwtchosen/WidgetSample.html, and the source link is fixed.

Thanks for reporting!
