### ISSUE TITLE
"chzn-container" width will be overwritten

### ISSUE THREAD

**Issue by luxmar** [ArcBees/gwtchosen#165]
As in https://github.com/ArcBees/gwtchosen/issues/114 I had the same prolem as confile.

So I extendet the resource (css) and added the following line
```width: 100% !important;```
 in the
```.chzn-container .chzn-drop {```
section as workaround.

Without the <b>!important</b> statement it is not working because it will always be overwritten with fix definde pixels as you can see in the attachment:
![bildschirmfoto vom 2014-10-06 18 03 17](https://cloud.githubusercontent.com/assets/7394438/4528815/5c713548-4d72-11e4-8ada-10fd5c9a118b.png)

I am working with gwtchosen 2.0.0-snapshot.

**Comment by jasonlemay** [comment]
@olafleur Width is dynamically calculated, so the style is appended inline. We can not really change that, therefore the use of `!important` is required, like shown in this example.
