### ISSUE TITLE
Search field input is too small

### ISSUE THREAD

**Issue by jasonlemay** [ArcBees/gwtchosen#181]
Looks like the height for `.chzn-container-multi .chzn-choices .search-field input` is too small, causing the search label to be vertically truncated. Height should be 10px more.

![screen shot 2015-01-07 at 5 13 16 pm](https://cloud.githubusercontent.com/assets/2584073/5654405/855326bc-9690-11e4-8245-08ee2f62197f.png)

**Comment by jDramaix** [comment]
@jasonlemay  This is a css issue ?

**Comment by jasonlemay** [comment]
I would think so. It's about Chosen CSS or one of my CSS file messing the Chosen style ... I will need to check on a fresh install where only Chosen is running

**Comment by jDramaix** [comment]
You can use the sample application ! Ask someone to help you for that

**Comment by payammeyer** [comment]
We are experiencing the same issue, we use gwtbootstrap and this is what we see:

![image](https://cloud.githubusercontent.com/assets/9900587/6396466/9a6e1032-bdac-11e4-8950-ea874f6ff0ea.png)

The selections look ok, but when you start typing to filter, 75% of the text is not shown.

**Comment by jasonlemay** [comment]
@olafleur Looks like it has been fixed with Chosen 3.0? The sample is not showing any bugs like that anymore.
