### ISSUE TITLE
Item list disappear under other elements

### ISSUE THREAD

**Issue by einevea** [ArcBees/gwtchosen#182]
Hi all,

Im wondering how can you define the number of items that are displayed in the item list. Im have a long list (countries) in a GXT dialog and when the list reaches the button area at the bottom of the dialog, the list disappear.

I can solve this by either make the list be on the top of all the elements or by limiting the visible number of items in the list.
![screen shot 2015-01-15 at 10 04 59](https://cloud.githubusercontent.com/assets/1064567/5755570/1292347e-9c9e-11e4-8fff-63fbd77e7038.png)

**Comment by meriouma** [comment]
You can reduce the `max-height` of `.chzn-results`
