### ISSUE TITLE
Add ability to ignore null values

### ISSUE THREAD

**Issue by christiangoudreau** [ArcBees/gwtchosen#183]
Sometimes, we have null as an acceptable values, but we don't want the user to be able to select it.

We should add the ability to ignore those null values form the selection and use the placeholder when the value = null.

**Comment by meriouma** [comment]
Which Chosen widget?

**Comment by meriouma** [comment]
From the tests I've done, I do believe that's the behaviour when you use `new ChosenOptions().setAllowSingleDeselect(true)` and that `null` is part of the acceptable values

**Comment by christiangoudreau** [comment]
No, I meant to "ignore" the null value. Not show it in the list, but still accept it if there's a null value (Talk with SP for more information)

**Comment by meriouma** [comment]
As I said, it's the actual behavior. You need 2 things : use `setAllowSingleDeselect(true)` on ChosenOptions and the rest of the solution is in the javadoc : **You have to pass null as first element of your collections**
```
/**
     * Set the list of the values that will be accepted by the widget.
     * <p/>
     * Calling this method will not reset the current selected value(s) except if this(ese) value(s) is(are) not in
     * the accepted values list anymore.
     * <p/>
     * With {@link com.arcbees.chosen.client.gwt.ChosenValueListBox}, if you want to display the placeHolder message
     * or be able to reset the component by passing null. You have to pass null as first element of your collections
     */
    public void setAcceptableValues(Collection<T> acceptableValues) {
```

**Comment by christiangoudreau** [comment]
@spg
