### ISSUE TITLE
Copyrights

### ISSUE THREAD

**Issue by spg** [ArcBees/gwtchosen#186]
Here's the state of copyrights in the project:

All `.java` files:` Copyright 2014 ArcBees Inc.`
except for com.arcbees.chosen.widgetsample.client.WidgetSample, where we use `Copyright (C) 2012 Julien Dramaix`

LICENSE.md: we use `Copyright (c) 2012, Julien Dramaix`

boostrap.css: `Copyright 2012 Twitter, Inc`

Suggestion:
* Apply `Copyright 2014 ArcBees Inc.` in all `.java` files
* Delete the root `LICENSE.md` file
* Leave the `Copyright 2012 Twitter, Inc` intact

**Comment by christiangoudreau** [comment]
The root license could be kept, but updated.

Aside of that, agreed!
