### ISSUE TITLE
Error at compilation when adding gwtchosen to application

### ISSUE THREAD

**Issue by Ethernano** [ArcBees/gwtchosen#199]
Hello, 
I wanted to try the new version of GwtChosen (2.0.0, maven repository version), but I get some trouble. The compilation fail when I add the inheritance in my application gwt xml : 
`<inherits name='com.arcbees.chosen.Chosen' />`

Here is the stacktrace I get when I try to compile : 
https://gist.github.com/Ethernano/5523fb9ae86d58396f6d

I can't figure out why, look like a problem with resources. I have tried to remove the old version of gwtChosen (1.2.0) we used, and tried on an application without gwtChosen, and I still get the same problem.

I'm very interested in the server-side filtering of the new version, since we have to handle with a lot of data (10k to 100k for some criteria), that's the feature I missed the most in the previous version. 

Thanks for your time (and this awesome widget). 
Guillaume.

**Comment by christiangoudreau** [comment]
Uhm, what is your version of Java? There's a line in the stacktrace that could be linked to the Java version that you're using

**Comment by christiangoudreau** [comment]
Caused by: java.lang.UnsupportedClassVersionError: com/google/gwt/thirdparty/common/css/SubstitutionMap : Unsupported major.minor version 51.0

This line to be exact

**Comment by jDramaix** [comment]
it's because we have enabled GSS and GSS requires Java 7.

**Comment by Ethernano** [comment]
Oh ok, that'll teach me to procrastinate on update my environment... I didn't think of that. 
That was it, works much better now. 
Thanks a lot for your help !

**Comment by wadezang** [comment]
Hi jDramaix. I have the same error "com/google/gwt/thirdparty/common/css/SubstitutionMap : Unsupported major.minor version 51.0". 
Currently I have installed Eclipse Luna, GPE with GWT 2.7, GXT 4 and Java 1.6 (Java 1.6 is currently required). The error came out only when I add a GXT Widget. It was not a problem for GWT 2.7 alone. 
As you mentioned above, the GSS requires Java 7. Is there a workaround to make it compatible with Java 6?
