### ISSUE TITLE
chosen-sprite.png not found

### ISSUE THREAD

**Issue by jDramaix** [ArcBees/gwtchosen#2]
All icons used by chosen are gathered in one file : chosen-sprite.png. This file is located in the public folder of the library and is deployed in folder containing all js files generated by GWT.

The problem is if the html page loading the javascript is in an other directory, the chosen-sprite cannot be found by the css. 

**Workaround** : copy this file in the same directory of your html file.

**Comment by DannyFeliz** [comment]
What you can do is just find in the chosen css all part where chosen-sprite.png is mentioned, then just make a path pointing where you put your chosen-sprite.png. E.g ../img/chosen-sprite.png

**Comment by pwnbit** [comment]
![chosen-sprite](https://user-images.githubusercontent.com/20031110/29593513-c0aa22da-87e5-11e7-891f-00eeee2a22b6.png)

Download it =)
