### ISSUE TITLE
Dropdown keeps showing after selecting or clicking outside of the area

### ISSUE THREAD

**Issue by christiangoudreau** [ArcBees/gwtchosen#207]
![screen shot 2015-03-17 at 11 47 13 am](https://cloud.githubusercontent.com/assets/853945/6691177/7daba100-cc9b-11e4-9173-0e4872b8f5d4.png)

**Comment by christiangoudreau** [comment]
@jclariviere @jDramaix @meriouma 

This happens in clients projects as well, we need to figure it out and fix it.

**Comment by jDramaix** [comment]
Do this bug appear after the last change in the dropdown position ?

**Comment by christiangoudreau** [comment]
The last change hasn't been merged yet

**Comment by christiangoudreau** [comment]
You think it's already fixed with SP last PR?

**Comment by jDramaix** [comment]
Nope it shouldn't be

**Comment by christiangoudreau** [comment]
??? As in, yes it should work, no SP didn't fix it or no the bug shouldn't be there? :D

**Comment by jDramaix** [comment]
> You think it's already fixed with SP last PR?
No it shouldn't be fixed by the last SP PR. :p

**Comment by christiangoudreau** [comment]
When are you back? This affects Bruce...

**Comment by jDramaix** [comment]
Monday
