### ISSUE TITLE
GWTChosen does not work with GWT 2.8.0-SNAPSHOT

### ISSUE THREAD

**Issue by bauna** [ArcBees/gwtchosen#214]
I know that is still snapshot but I have used it on production and it's pretty stable.
Here I made a [fork](https://github.com/bauna/gwtchosen/tree/gwt280) with necessary changes to run it with GWT 2.8.0-SNAPSHOT

**Comment by jDramaix** [comment]
you simply need to use the gwtquery snapshot ?

**Comment by bauna** [comment]
I have already updated the gwtchosen pom to use that: https://github.com/bauna/gwtchosen/blob/gwt280/pom.xml#L70

And then when I run the sample project, select tags are not converted to chosen.

**Comment by bauna** [comment]
I have tracked and fixed the issue GWTQuery.
Here is the pull request request: https://github.com/ArcBees/gwtquery/pull/351
