### ISSUE TITLE
With Placement.AUTO, when filtering elements the chosen container may switch direction

### ISSUE THREAD

**Issue by Chris-V** [ArcBees/gwtchosen#217]
Steps to reproduce:
- Create a chosen element with Placement.AUTO
- Make sure it is close to the bottom boundary so that when you open it, it is displayed as ABOVE
- Filter the content. If the container has enough space to display as BELOW, it will do so.

Expected: When filtering, the chosen container should not move, so that the UI stays stable.

**Comment by christiangoudreau** [comment]
@jDramaix It needs to be fixed asap!

**Comment by jDramaix** [comment]
Will work on chosen tomorrow
