### ISSUE TITLE
Null as first element in setAcceptableValues doesn't work

### ISSUE THREAD

**Issue by foal** [ArcBees/gwtchosen#255]
I have a  new ChosenValueListBox<>(new ModelNameRenderer<ReservationUnitModel>(), new ModelIdProvidesKey<ReservationUnitModel>());

From setAcceptableValues documentation: With com.arcbees.chosen.client.gwt.ChosenValueListBox, if you want to display the placeHolder message or be able to reset the component by passing null. You have to pass null as first element of your collections

So I do the following:
```Java
        final List<T> values = getValues();
        final List<T> elementsWithFirstNull = new ArrayList<>(values.size() + 1);
        elementsWithFirstNull.add(null);
        elementsWithFirstNull.addAll(values);
        listBox.setAcceptableValues(elementsWithFirstNull);
```
After that the list box show me as a first element the null.
![image](https://cloud.githubusercontent.com/assets/458209/9143974/fea3bed6-3d49-11e5-9926-a8f716e515a0.png)

ModelNameRenderer:
```Java
     public String render(final D s) {
        return s == null ? null : s.getName();
    }
```
ModelIdProvidesKey
```Java
        public Object getKey(final M i) {
		return i == null ? null : i.getId();
	}
```
I am expect to see placeHolder :)

**Comment by meriouma** [comment]
Your renderer should be 
```
public String render(final D s) {
        return s == null ? "" : s.getName();
}
```

**Comment by foal** [comment]
O_o! Great, it works :+1: 

Thank you for help.
