### ISSUE TITLE
ChosenValueListBox on change event is not fired

### ISSUE THREAD

**Issue by imrabti** [ArcBees/gwtchosen#269]
With the release on GWT-Chosen 3.0 there is regression where the onChange event in the ChosenValueListBox is never fired and the selected value is all the time null.

**Comment by olafleur** [comment]
@meriouma @jasonlemay could you look at that?

**Comment by meriouma** [comment]
Please reopen the issue if it still happens with new 3.1-SNAPSHOT. Thanks!
