### ISSUE TITLE
Error on demo page in custom filtering

### ISSUE THREAD

**Issue by wyssen** [ArcBees/gwtchosen#270]
Hi
Sorry to write an issue here, but on the google plus page, nobody did answer on my comment.
There is a bug on the demo page http://dev.arcbees.com/gwtchosen/
The example "Custom filtering" does not work. If you check out the listbox just under the text "Example: Start typing some characters to see the list of items", you can see a 27px wide listbox. If you toggle it open, it keeps this width (so you cannot see any values in the listbox). If you type, the filter does apparently not work, since the height of the dropdown stays the same all the time, no matter what you type.
Is this feature still in progress or do you have a bug on the demo page?
This behavior occurs with Chrome Version 45.0.2454.101 m, Firefox 41.0
![2015-09-29 09_47_21-gwt-chosen](https://cloud.githubusercontent.com/assets/9450822/10241447/552474ec-68e9-11e5-80ac-6c545394286b.png)

**Comment by christiangoudreau** [comment]
You don't have to be sorry! Thanks for reporting here!

**Comment by olafleur** [comment]
In fact, I did a pull request to fix that (https://github.com/ArcBees/dev-site/pull/127) but I forgot that the deployment wasn't automatic. @Chris-V could you deploy the master branch ?

**Comment by olafleur** [comment]
The new version has been deployed. Thanks for your input!

**Comment by wyssen** [comment]
Thank you for the correction, but it is only partially corrected :)
The filter still does not apply. You only corrected the width problem. If you type, the list stays the same. And the first time the list opens (after a refresh of the page), the list stays empty. You need to open it a second time in order to get the list populated. However, when filtering by typing anything, the list does not change.
