### ISSUE TITLE
Error "this.selectedItem is undefined" when add new items to ChosenListBox and update it

### ISSUE THREAD

**Issue by conargon** [ArcBees/gwtchosen#271]
I'm testing the new **ChosenListBox release 3.0**. When I add new items dinamically or when I set some items as selected, I get the exception **this.selectedItem is undefined**.

Test code:

```java
	public void onModuleLoad() {
		final Button testButton = new Button("Test");
		
		final ChosenListBox chosen = new ChosenListBox(true);
		chosen.setWidth("100%");
		chosen.addItem("uno");
		chosen.addItem("dos");
		chosen.addItem("tres");

		RootPanel.get("chosenContainer").add(chosen);
		RootPanel.get("sendButtonContainer").add(testButton);
		
		testButton.addClickHandler(new ClickHandler() {
			public void onClick(ClickEvent event) {
				chosen.addItem("cuatro");
				chosen.addItem("cinco");
				chosen.addItem("seis");
				chosen.update();
//				chosen.setItemSelected(0, true);
			}
		});
	}
```

I debugged the Java source and I saw the *GQuery selectedItem* private attribute of *ChosenImpl* class is never initialized when the *ChosenListBox* is multivalue.This is, the method *initSearchElement*, where the attribute *selectedItem* is initialized, is never called in this case.

The problem is that the method *update()* of ChosenListBox class fires events, and the handler vents  references to *selectedItem*. See method *update()* of *DesktopMultipleChosenImpl* class and finally method *resultsResetCleanup* of *ChosenImpl* class. This last method references to selectedItem and crash.

I think the method *initSearchElement* of *DesktopMultipleChosenImpl* class should initialize selectedItem attribute.

**Comment by christiangoudreau** [comment]
Thanks for sharing this with us! We'll look into this.

**Comment by meriouma** [comment]
Please reopen the issue if it still happens with new 3.1-SNAPSHOT. Thanks!
