### ISSUE TITLE
opt group dissapears on mobile gwtchosen view when select/deselecting its options

### ISSUE THREAD

**Issue by elmentecato** [ArcBees/gwtchosen#292]
Using 3.1-SNAPSHOT I have the following ChosenListBox:

(UIBinder)
```
<chzn:ChosenListBox ui:field="lb" disableSearchThreshold="10" multipleSelect="true">
</chzn:ChosenListBox>
```

with the following options (couldn't find a way to create opt groups in UIBinder):

```java
lb.addGroup("Container A");
lb.addItemToGroup("Auth Policy 1");
lb.addItemToGroup("Auth Policy 2");
lb.addItemToGroup("Auth Policy 3");
lb.addItemToGroup("Auth Policy 4");
lb.addGroup("Container B");
lb.addItemToGroup("Auth Policy 5");
lb.addItemToGroup("Auth Policy 6");
lb.addItemToGroup("Auth Policy 7");
lb.addItemToGroup("Auth Policy 8");
lb.addItemToGroup("Auth Policy 9");
lb.addGroup("Container C");
lb.addItemToGroup("Auth Policy 10");
lb.addItemToGroup("Auth Policy 11");
```

If I run it on a mobile device, I see this:

![gwtchosen-group-dissapears-bug1](https://cloud.githubusercontent.com/assets/1129084/11489081/4d9de644-9789-11e5-9aad-a9185b747a31.png)

If I select and then deselect the two options for "Container C", the screen now looks like this:

![gwtchosen-group-dissapears-bug2](https://cloud.githubusercontent.com/assets/1129084/11489098/76d7df06-9789-11e5-8a47-d4d76c8a7cdb.png)

The opt group "Container C" is not present anymore. Is there a workaround for this issue?

**Comment by jasonlemay** [comment]
@elmentecato Have a look at the associated pull request, that should fix your problem. I also added a better style for the optgroup on mobile, but you can always overwrite it!

**Comment by elmentecato** [comment]
Nice... hope to have it soon in master/3.1-SNAPSHOT. Thanks.
