### ISSUE TITLE
Support for boolean operators in Multiple chosen list box

### ISSUE THREAD

**Issue by IanMayo** [ArcBees/gwtchosen#36]
I believe it's a fairly common usage to use GWTChosen to build up fields for a faceted search (in the countries example this would be selecting items in the control to trigger a "search for results in Brazil and Algeria").

It would be a  great step forward to include a boolean +/- UI toggle element at the left-hand side of the widget.  So, after adding Brazil and Algeria items to the multi-select, the user could click on the + icon at the left-hand of the Algeria widget. The '+' would turn into '-', and the app would process this as "search for results in Brazil but not Algeria".

I'm not familiar with the development flow of the widget - maybe the normal flow would be for this to be included in Chosen and then cascade into gwtchosen.

**Comment by olafleur** [comment]
I don't think we want that in the general case, but I think it would make a great usage example of GWTChosen. We are in the process of transfering the docs to our new website, but feel free to contribute an example of that in the docs!
