### ISSUE TITLE
The list of item should appear under or above the ChosenListBox button.

### ISSUE THREAD

**Issue by Regnoult** [ArcBees/gwtchosen#61]
Context:
When a  ChosenListBox button is "unfortunately"  at the bottom of the screen, then  when I click on the button so the list appears under the button...This has the effect to "destroy my layout".

Issue:
The chosen widget does not automatically use the free visible space on the screen...The list of items should be displayed vertically in 2 directions (above or under the button).

Image illustrating the case:
![under-above-illustration](https://f.cloud.github.com/assets/978518/142137/ffd08568-72c7-11e2-9c94-3026e8d5f603.jpg)

**Comment by meriouma** [comment]
Handled by #200
