### ISSUE TITLE
Why it runs very slow under GWT DevMode when the list is big?

### ISSUE THREAD

**Issue by AlQuraian** [ArcBees/gwtchosen#75]
I tried a few example and tested my own, and I see that it's unbearably slow when in dev mode, however, it runs fine when I compile it. It seems slow when the list is around or over 100.

**Comment by meriouma** [comment]
Is it with dev-mode or Super-dev-mode? If it's with DevMode, it is now deprecated so I suggest you move to SDM

**Comment by jDramaix** [comment]
yep we can close this issue. It shouldn't be slow anymore under super-dev-mode
